# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Workspace(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'WorkspaceStatus',
        'endpoints': 'list[Endpoint]',
        'storage': 'Storage'
    }

    attribute_map = {
        'status': 'status',
        'endpoints': 'endpoints',
        'storage': 'storage'
    }

    def __init__(self, status=None, endpoints=None, storage=None):  # noqa: E501
        """Workspace - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._endpoints = None
        self._storage = None
        self.discriminator = None
        self.status = status
        if endpoints is not None:
            self.endpoints = endpoints
        if storage is not None:
            self.storage = storage

    @property
    def status(self):
        """Gets the status of this Workspace.  # noqa: E501


        :return: The status of this Workspace.  # noqa: E501
        :rtype: WorkspaceStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Workspace.


        :param status: The status of this Workspace.  # noqa: E501
        :type: WorkspaceStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def endpoints(self):
        """Gets the endpoints of this Workspace.  # noqa: E501


        :return: The endpoints of this Workspace.  # noqa: E501
        :rtype: list[Endpoint]
        """
        return self._endpoints

    @endpoints.setter
    def endpoints(self, endpoints):
        """Sets the endpoints of this Workspace.


        :param endpoints: The endpoints of this Workspace.  # noqa: E501
        :type: list[Endpoint]
        """

        self._endpoints = endpoints

    @property
    def storage(self):
        """Gets the storage of this Workspace.  # noqa: E501


        :return: The storage of this Workspace.  # noqa: E501
        :rtype: Storage
        """
        return self._storage

    @storage.setter
    def storage(self, storage):
        """Sets the storage of this Workspace.


        :param storage: The storage of this Workspace.  # noqa: E501
        :type: Storage
        """

        self._storage = storage

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Workspace, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Workspace):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
