sudo: required
os:
  - linux
language: cpp
dist: bionic

services:
  - docker

jobs:
  include:

    - stage: build (compile, unit test, package)
      install: skip
      script: travis/build.sh

    - stage: container creation and publishing
      install: skip
      script: travis/containerCreation.sh

    - stage: smoke and acceptance test
      install: skip
      script: travis/acceptanceTest.sh

    - stage: release
      if: branch = master AND NOT type IN (pull_request)
      install: skip
      script: travis/release.sh

import:
  - docs/.travis.yml

notifications:
  slack: eoepca:Msk9hjQKAbwSYcVWiepenPim
  email:
    recipients:
      - a.person@acme.com
      - a.n.other@acme.com
    on_success: never # default: change
    on_failure: never # default: always
