[[components]]
= Components Design

[NOTE]
.Content Description
================================
This section contains:

* A concise breakdown of the Building Block in several independent services (when applicable). For each component, the following subsections are added:
** Overview and purpose: indicating the functionality covered by the component
** SW Reuse and Dependencies: indicating reuse of third party open source solutions (if any) and any pre-required Dependencies
** Interfaces: both internal to the building block and those exposed externally
** Data: Data usage of the building block, data flow and any GDPR concerns should be addressed here
** Applicable Resources: links and references to (Reference Docs), and repositories.

When a breakdown is necessary, a genral overview of the building block can be given. On the contrary, no breakdown indicates a single component development with the same expected sections.

================================

== ADES Core Framework
=== Overview and Purpose

The ADES Core Framework is the main software container for all the components composing the ADES.

=== Software Reuse and Dependencies

All software and their dependecies are described in the nextr sections

=== Interfaces

All interfaces are external and described in the <<interfaces>> section

=== Data

Not applicable

=== Applicable Resources

* <<TB13-ADES>>
* <<TB14-WPS-T>>

== WPS Server
=== Overview and Purpose

The WPS Server provides the processing interfaces of the ADES. Basically, it exposes 2 web services:

* OGC Web Services Common <<OGC-COMMON>> hosting WPS 1.0.0 & 2.0.0 processing services
* OGC API Processes <<OGC-API-PROC>> hosting WPS in RESTful core OpenAPI

==== WPS 1.0 & 2.0 compliance

_"ZOO-Kernel implements and complies with the WPS 1.0.0 and the WPS 2.0.0 standards edited by the Open Geospatial Consortium"._ 
The Dismiss operation, which is _"only available in WPS 2.0.0, it lets the client ask the server to stop a running service and remove any file it created"_, requires changes in the source code to support the EMS operations. The current ZOO-Kernel implementation relies on local processes which are being removed from the execution environment. This approach prevents the management of remote processes. In this context, the ZOO-Kernel third-party software is modified to allow managing remote execution via APIs, in particular when the remote process exposes an OGC WPS-T 2.0.0 interface. It is foreseen an upstream contribution to the open-source ZOO-Project project.

==== OGC API Processes compliance

The ZOO-Project product, available at www.zoo-project.org, is an open-source implementation of both the Web Processing Service (WPS) standard (version 1.0.0 and 2.0) and the OGC API - Processes specification. The ZOO-Kernel is the main component written in C which enables the deployment of geospatial processes on the Web in a way that conforms to OGC standards.footnote:[https://docs.ogc.org/per/19-062.html#_zoo_project <<OGC-API-HACK2019>> 

=== Software Reuse and Dependencies

The following open-source software is reused:

** ZOO-Kernel http://zoo-project.org/docs/kernel/

=== Interfaces

The WPS Server exposes the OGC OWS services WPS 1.0 & WPS 2.0 as well as an OGC API Processes. According to their respective specifications, they allow to deploy, execute, monitor and dismiss processing services.
More details in the <<interfaces>> section.

=== Data

Not Applicable.

=== Applicable Resources

* <<OGC-COMMON>>
* <<OGC-WPS>>
* <<OGC-WPS2>>
* <<OGC-API-PROC>>
* <<OGC-API-HACK2019>>

[#appservice]
== Services

Services are the core elements performing the jobs submission by the users
Indeed, when a user <<Deploy Processing Service,deploys>> a service on the ADES, this latter prepares a service from the Application Package.
This Service shall be composed of the <<CWL Parser,workflow>> of the pplication of the user and enhanced with <<Data Staging>> as pre and post processing steps of the workflow.

=== Overview and Purpose

The following diagram shows the component used by the Service component to enable the deployed application. 

.ADES Service Components Diagram
[plantuml, diagram-component, png] 
....
include::../include/servicesoverview.wsd[]
....

The Service component is in charge of orchestrating the application execution when the service in invoked by a <<Job Submision,job submission>> from the Web Processing Service layer.

=== Software Reuse and Dependencies

The following open-source software is reused:

* CWL Tool <<CWL>>
* Calrissian https://github.com/Duke-GCB/calrissian
* ZOO-Services http://zoo-project.org/docs/services/index.html

=== Data

* OWS Context
* CWL

=== Applicable Resources

* <<CWL>>
* <<ZOO>>



== OWS Context Parser
=== Overview and Purpose

The aim of the software component is to provide a library for parsing an OWS document.

=== Software Reuse and Dependencies

Software developed in C++ language with no particular dependencies

=== Interfaces

Not Applicable

=== Data

The https://github.com/EOEPCA/proc-comm-lib-ows/blob/develop/tests/application/assetes/ows1.xml[OWS Context file] describes the elements necessary for the publication of an EOEPCA/ADES service.

=== Applicable Resources

* <<OGC-OWC>>
* <<OGC-OWC-ATOM>>

== CWL Parser
=== Overview and Purpose

The software component is a shared library to provides the means to parse a Common Workflow Language Specification document.

The Common Workflow Language (CWL) targets data-intensive processing scenarios and to make these portable and scalable across platforms capable of interpreting and execute the processes by describing:
* A runtime environment
* A Workflow (DAG)
* Command line tool(s)
* Parameter of the process
* Inputs/outputs

=== Software Reuse and Dependencies

Software developed in C++ language with no particular dependencies

=== Interfaces

Not applicable

=== Data

https://github.com/EOEPCA/proc-ades/tree/develop/test/sample_apps

=== Applicable Resources

* <<CWL>>



