# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rm_client
from rm_client.api.default_api import DefaultApi  # noqa: E501
from rm_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_workspace_workspaces_post(self):
        """Test case for create_workspace_workspaces_post

        Create Workspace  # noqa: E501
        """
        pass

    def test_delete_workspace_workspaces_workspace_name_delete(self):
        """Test case for delete_workspace_workspaces_workspace_name_delete

        Delete Workspace  # noqa: E501
        """
        pass

    def test_get_workspace_workspaces_workspace_name_get(self):
        """Test case for get_workspace_workspaces_workspace_name_get

        Get Workspace  # noqa: E501
        """
        pass

    def test_patch_workspace_workspaces_workspace_name_patch(self):
        """Test case for patch_workspace_workspaces_workspace_name_patch

        Patch Workspace  # noqa: E501
        """
        pass

    def test_probe_probe_get(self):
        """Test case for probe_probe_get

        Probe  # noqa: E501
        """
        pass

    def test_register_workspaces_workspace_name_register_post(self):
        """Test case for register_workspaces_workspace_name_register_post

        Register  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
