# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rm_client
from rm_client.models.workspace_status import WorkspaceStatus  # noqa: E501
from rm_client.rest import ApiException


class TestWorkspaceStatus(unittest.TestCase):
    """WorkspaceStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspaceStatus(self):
        """Test WorkspaceStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rm_client.models.workspace_status.WorkspaceStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
