#!/opt/app-root/bin/python

import argparse
from webdav3.client import Client
from pathlib import Path
import os
path = Path("/here/your/path/file.txt")

parser = argparse.ArgumentParser(prog='publish_results', description='Publish results via http post')

parser.add_argument('-v', '--version', action='version', version='%(prog)s 1.0')
parser.add_argument('--source', '-s', dest='source',  required=True )
parser.add_argument('--remotePath', '-p', dest='remotePath',  required=True )
parser.add_argument('--destinationUrl','-d', dest='url',    required=True )
parser.add_argument('--authentication', '-a', dest='auth', help='authentication tuple <user>:<password>')

parser.add_argument('--user', '-u', dest='user' )
parser.add_argument('--password', '-P', dest='password' )

args = parser.parse_args()
source=args.source
remotePath=args.remotePath
url = args.url

if args.user is not None:
    user = args.user

if args.password is not None:
    password = args.password

if args.auth is not None:
    auth = args.auth.split(":")
    user = auth[0]
    password = auth[1]

if os.path.isfile(source):
    source = Path(source).parent

options = {
 'webdav_hostname': url,
 'webdav_login':    user,
 'webdav_password': password
}


client = Client(options)
client.upload_sync(remote_path=remotePath, local_path=source)

print(url+remotePath)