@startuml Service Component Diagram

hide stereotype

skinparam component<<tbd>> {
    BackgroundColor Crimson
    FontColor white
}

skinparam frame<<3rd>> {
    BackgroundColor CornFlowerBlue
    BorderColor DarkBlue
}

skinparam component<<reuse>> {
    BackgroundColor Khaki
    BorderColor Orange
}

package "ADES Container"{

    [Web Processing Service] as wps

    [Workflow Executor] as wfexe 

    package "**Processing Service**" as procservice{

        frame "OWS Context" as ows <<3rd>>
        frame "Application Workflow" as cwlapp <<3rd>>
    }

    wps --> cwlapp : read workflow
    wps --> ows : read service\ndescription

}

cloud "Processing Cluster"{

    database "Storage"{
        frame "Application Image" as appimg <<3rd>>
        database "Runtime volume" as volume
    }

    node "Application Container" as appcon {
        [Commands] <<reuse>> as commands
    }

    node "Staging Container" {
        [Stage-in] as stagein <<tbd>>
        [Stage-Out] as stageout <<tbd>>
    }

}

wfexe --> stagein : Stage-in data
wfexe --> stageout : Stage-out data
wfexe -down-> procservice : invokes

cwlapp --> commands : describes

appcon -- appimg : uses
appcon -- volume : mount

wps -down- wfexe : executes job
wps --> appimg : pull image

@enduml