apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ades.fullname" . }}
  labels:
    {{- include "ades.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "ades.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "ades.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ades.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          readinessProbe:
            httpGet:
              path: /terradue/wps3/processes
              port: http
              httpHeaders:
              - name: Accept
                value: application/json
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if .Values.useKubeProxy }}
            - name: HTTP_PROXY
              value: "http://{{ include "ades.fullname" . }}-kubeproxy:8001"
            {{- else }}
            - name: KUBECONFIG
              value: /var/etc/ades/kubeconfig
            {{- end }}
            - name: ADES_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: ADES_CWL_INPUTS
              value: /var/etc/ades/wfinputs.yaml
            - name: ADES_POD_ENV_VARS
              value: /var/etc/ades/pod_env_vars.yaml
            - name: ADES_POD_NODESELECTORS
              value: /var/etc/ades/pod_nodeselectors.yaml
            - name: STORAGE_CLASS
              value: {{ .Values.workflowExecutor.processingStorageClass | quote }}
            - name: VOLUME_TMP_SIZE
              value: {{ .Values.workflowExecutor.processingVolumeTmpSize | quote }}
            - name: VOLUME_OUTPUT_SIZE
              value: {{ .Values.workflowExecutor.processingVolumeOutputSize | quote }}
            - name: JOB_MAX_RAM
              value: {{ .Values.workflowExecutor.processingMaxRam | quote }}
            - name: JOB_MAX_CORES
              value: {{ .Values.workflowExecutor.processingMaxCores | quote }}
            - name: JOB_KEEPWORKSPACE
              value: {{ .Values.workflowExecutor.processingKeepWorkspace | quote }}
            - name: JOB_KEEPWORKSPACE_IF_FAILED
              value: {{ .Values.workflowExecutor.processingKeepWorkspaceIfFailed | quote }}
            - name: ADES_WFEXEC_MAINCWL
              value: /var/etc/ades/main.cwl
            - name: ADES_WFEXEC_STAGEIN_CWL
              value: /var/etc/ades/stagein.cwl
            - name: ADES_WFEXEC_STAGEOUT_CWL
              value: /var/etc/ades/stageout.cwl
            - name: ADES_WFEXEC_RULEZ_CWL
              value: /var/etc/ades/rulez.cwl
            - name: IMAGE_PULL_SECRETS
              value: /var/etc/ades/ppImagePullSecrets.json
            {{- if .Values.workflowExecutor.useResourceManager }}
            - name: USE_RESOURCE_MANAGER
              value: {{ .Values.workflowExecutor.useResourceManager | quote }}
            - name: RESOURCE_MANAGER_USERNAME
              value: {{ .Values.workflowExecutor.resourceManagerUser | quote }}
            - name: RESOURCE_MANAGER_ENDPOINT
              value: {{ .Values.workflowExecutor.resourceManagerEndpoint | quote }}
            - name: RESOURCE_MANAGER_WORKSPACE_PREFIX
              value: {{ .Values.workflowExecutor.resourceManagerWorkspacePrefix | quote }}
            {{- end }}
            {{- if .Values.workflowExecutor.backofflimit }}
            - name: ADES_BACKOFF_LIMIT
              value: {{ .Values.workflowExecutor.backofflimit| quote }}
            {{- end }}
            {{- if .Values.workflowExecutor.processingNodeSelector }}
            - name: ADES_NODE_SELECTOR
              value: {{ toJson .Values.workflowExecutor.processingNodeSelector| quote }}
            {{- else if .Values.nodeSelector }}
            - name: ADES_NODE_SELECTOR
              value: {{ toJson .Values.nodeSelector| quote }}
            {{- end }}
            {{- if .Values.workflowExecutor.platformDomain }}
            - name: ADES_PLATFORM_DOMAIN
              value: {{ .Values.workflowExecutor.platformDomain| quote }}
            {{- end }}
            {{- if .Values.wps.pepClientStatePath }}
            - name: PEP_CLIENT_STATE_PATH
              value: {{ .Values.wps.pepClientStatePath| quote }}
            {{- end }}
            {{- if .Values.workflowExecutor.jobNamespaceLabels }}
            - name: ADES_JOB_NAMESPACE_LABELS
              value: {{ toJson .Values.workflowExecutor.jobNamespaceLabels| quote }}
            {{- end }}
            {{- if .Values.workflowExecutor.calrissianImage }}
            - name: CALRISSIAN_IMAGE
              value: {{ .Values.workflowExecutor.calrissianImage | quote }}
            {{- end }}

          volumeMounts:
            - name: ades-config
              mountPath: /var/etc/ades
            - name: ades-user-data
              mountPath: /var/www/_run/res
            - name: ades-processing-services
              mountPath: /opt/zooservices_user
            - name: ades-config
              mountPath: /zooservices/main.cfg
              subPath: maincfg
            - name: ades-config
              mountPath: /opt/error_message_templates/error_message_templates.json
              subPath: error_messages.json
      volumes:
        - name: ades-config
          configMap:
            name: {{ template "ades.fullname" . }}-configmap
        - name: ades-user-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.existingUserDataClaim }}
            claimName: {{ .Values.persistence.existingUserDataClaim }}
            {{- else }}
            claimName: {{ template "ades.fullname" . }}-user-data
            {{- end -}}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: ades-processing-services
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.existingProcessingServicesClaim }}
            claimName: {{ .Values.persistence.existingProcessingServicesClaim }}
            {{- else }}
            claimName: {{ template "ades.fullname" . }}-processing-services
            {{- end -}}
        {{- else }}
          emptyDir: {}
        {{- end }}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
