# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StorageUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'quota_in_mb': 'int'
    }

    attribute_map = {
        'quota_in_mb': 'quota_in_mb'
    }

    def __init__(self, quota_in_mb=None):  # noqa: E501
        """StorageUpdate - a model defined in Swagger"""  # noqa: E501
        self._quota_in_mb = None
        self.discriminator = None
        self.quota_in_mb = quota_in_mb

    @property
    def quota_in_mb(self):
        """Gets the quota_in_mb of this StorageUpdate.  # noqa: E501


        :return: The quota_in_mb of this StorageUpdate.  # noqa: E501
        :rtype: int
        """
        return self._quota_in_mb

    @quota_in_mb.setter
    def quota_in_mb(self, quota_in_mb):
        """Sets the quota_in_mb of this StorageUpdate.


        :param quota_in_mb: The quota_in_mb of this StorageUpdate.  # noqa: E501
        :type: int
        """
        if quota_in_mb is None:
            raise ValueError("Invalid value for `quota_in_mb`, must not be `None`")  # noqa: E501

        self._quota_in_mb = quota_in_mb

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StorageUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StorageUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
