kind: Service
apiVersion: v1
metadata:
  name: ades
  labels:
      app: ades
spec:
  selector:
    app: ades
  ports:
  - name: http
    protocol: TCP
    port: 80
  type: ClusterIP
  externalIPs:
      - "195.201.250.29"
