apiVersion: v1
kind: PersistentVolume
metadata:
  name: ades-user-data-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: glusterfs-storage
  hostPath:
    # type: Directory
    path: /var/ades/userdata