apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ades-user-data-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: glusterfs-storage
  resources:
    requests:
      storage: 10Gi