name: workflow_executor_env
channels:
  - eoepca
  - conda-forge
  - terradue
  - defaults
dependencies:
  - cwl-wrapper=0.8.0
  - click=7.1.2
  - fastapi=0.65.0
  - python-kubernetes=12.0.0
  - uvicorn=0.13.4
  - jinja2=2.10
  - fastapi==0.65.0
  - cwl-wrapper==0.8.0
  - uvicorn==0.13.4
  - pip
  - pip:
      - pytest-kind
      - boto3==1.17.53
      - eoepca-scim==2.7.4
      - lxml==4.6.3
      - pycrypto==2.6.1
      - pyjwkest==1.4.2
      - robotframework==3.2.2
      - WellKnownHandler==0.2.0
      - OWSLib==0.24.1
      - folium==0.12.1
      - geolinks==0.2.0
      - bs4==0.0.1
      - tifffile==2021.4.8
      - awscli==1.19.53
