package:
  name: workflow_executor
  version: 1.0.0

source:
  path: ./

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-kubernetes
    - fastapi
    - click
    - cwl-wrapper
    - uvicorn
    - jinja2

test:
  imports:
    - workflow_executor
    - kubernetes

about:
  home:
