[[mainComponents]]
= Building Block Design

[NOTE]
.Content Description
================================
This section contains:

* A concise breakdown of the Building Block in several independent services (when applicable). For each component, the following subsections are added:
** Overview and purpose: indicating the functionality covered by the component
** SW Reuse and Dependencies: indicating reuse of third party open source solutions (if any) and any pre-required Dependencies
** Interfaces: both internal to the building block and those exposed externally
** Data: Data usage of the building block, data flow and any GDPR concerns should be addressed here
** Applicable Resources: links and references to (Reference Docs), and repositories.

When a breakdown is necessary, a genral overview of the building block can be given. On the contrary, no breakdown indicates a single component development with the same expected sections.

================================

== WPS Server
=== Overview and Purpose

The WPS Server provides the external interface of the ADES, available to the EMS only. 

==== WPS-T 2.0.0 compliance

_"ZOO-Kernel implements and complies with the WPS 1.0.0 and the WPS 2.0.0 standards edited by the Open Geospatial Consortium"._
The Dismiss operation, which is _"only available in WPS 2.0.0, it lets the client ask the server to stop a running service and remove any file it created"_, requires changes in the source code to support the EMS operations. The current ZOO-Kernel implementation relies on local processes which are being removed from the execution environment. This approach prevents the management of remote processes. In this context the ZOO-Kernel third-party software is modified to allow managing remote execution via APIs, in particular when the remote process exposes an OGC WPS-T 2.0.0 interface. It is foreseen an upstream contribution to the open-source ZOO-Project project.

=== Software Reuse and Dependencies

The following open-source software is reused:

* WPS Server
** ZOO-Kernel http://zoo-project.org/docs/kernel/

=== Interfaces

The WPS Server exposes an OGC WPS-T 2.0.0 (REST/JSON) <<WPS-T>> <<WPS-REST-JSON>> interface to deploy, execute, monitor and dismiss processing services.

=== Data
=== Applicable Resources

== ADES Core Engine
=== Overview and Purpose
=== Software Reuse and Dependencies
=== Interfaces
=== Data
=== Applicable Resources
